/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dynamicProgramming;

public class StrangePrinter {

    private int strangePrinter(String s, int start, int end, char defaultChar) {
        while(start <= end && s.charAt(start) == defaultChar) start++;

        if (start > end) return 0;

        int minCost = 1 + strangePrinter(s, start+1, end, defaultChar);

        for(int index = start+1 ; index <= end ; index++) {
            if (s.charAt(index) == s.charAt(start)) {
                int cost = 1 + strangePrinter(s, start, index, s.charAt(start)) + strangePrinter(s, Integer.min(index+1, end), end, defaultChar);
                minCost = Integer.min(minCost, cost);
            }
        }
        return minCost;
    }
    public int strangePrinter(String s) {
        return 1+Integer.min(
                strangePrinter(s, 0, s.length()-1, s.charAt(0)),
                strangePrinter(s, 0, s.length()-1, s.charAt(s.length()-1))
        );
    }
}
